POST http://localhost:4004/odata/v4/admin/Incidents HTTP/1.1
Content-Type: application/json

{
   "customer_ID":"C001",
   "title":"Incident created from api",
   "urgency_code":"M",
   "status_code":"I"
}


###
POST http://localhost:4004/odata/v4/admin/Addresses HTTP/1.1
Content-Type: application/json

{
   "streetAddress":"123 Main St"
}
 
###
POST http://localhost:4004/odata/v4/admin/Customers HTTP/1.1
Content-Type: application/json
